springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zcunsoft.tracking.api.controllers
server:
  port: 8087
spring:
  application.name: trackingapi
  datasource:
    clickhouse:
      jdbc-url: jdbc:clickhouse://10.10.220.188:8123/default
      username: default
      password:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
#    generate-ddl: true
logging:
  file:
    path: log
trackingapi:
  access-control-allow-origin: "*"
