server:
  port: 8080
spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://10.10.223.231:3306/advdb?characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    clickhouse:
      jdbc-url: jdbc:clickhouse://114.80.106.44:8123/sensors
      username: default
      password: cEqmCx27Xg7t
#      jdbc-url: jdbc:clickhouse://10.10.220.188:8123/default
#      username: default
#      password:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      #         driver-class-name: cc.blynk.clickhouse.ClickHouseDriver
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
#    generate-ddl: true
  redis:
    # 地址
    host: 10.10.223.104
    # 端口，默认为6379
    port: 6379
    database: 0
logging:
  file:
    path: log
token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 300
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
trackingreport:
  tenant-dept: 102